#define fLUT_Name Urban_Cinematic_MLUT
#define fLUT_LutList "FOREST918-DARK-ROMAN-HENSE\0FOREST918-LIGHT-ROMAN-HENSE\0URBAN918-DARK-S-LOG3-ROMAN-HENSE\0URBAN918-LIGHT-S-LOG3-ROMAN-HENSE\0URBANBLUES-DARK-S-LOG3-ROMAN-HENSE\0URBANBLUES-LIGHT-S-LOG3-ROMAN-HENSE\0"
#define fLUT_TextureName "Urban Cinematic MLUT.png"
#define fLUT_TileSizeXY 64
#define fLUT_TileAmount 64
#define fLUT_LutAmount 6
#include "_BaseLUT.fxh"
